# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present


      # - name: Publish
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: 'massa_*'

#   open_pr:
#
#     runs-on: ubuntu-latest
#
#     steps:
#     - name: Checkout massa-unit-tests-src
#       uses: actions/checkout@v3
#       with:
#         path: unit_tests
#
#     - name: Checkout massa repo
#       uses: actions/checkout@v3
#       with:
#         repository: massalabs/massa
#         path: massa
#         ref: prepare_testnet_15
#
#     - name: Copy ts files
#       shell: bash
#       run: |
#         ls -alh unit_tests/
#         ls -alh massa/
#         ls -alh ./
#         cp -v unit_tests/assembly/massa/datastore.ts massa/massa-execution-worker/src/tests/wasm/sources/datastore/main.ts
#         cd massa
#         git --no-pager status
#         git --no-pager diff
#
#     - uses: peter-evans/create-pull-request@v4
#       with:
#         path: massa