name: Release

on:
  push:
    tags:
      - TEST.*
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest]
        platform: [x86_64]
        include:
          - os: ubuntu-latest
            platform: x86_64
            target: x86_64-unknown-linux-gnu
            name: release_linux.tar.gz
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Package
        shell: bash
        run: |
          mkdir massa_unit_tests && cd massa_unit_tests
          
          cp -v ../build/massa/datastore.wasm ./
          cp -rv ../assembly/massa ./
          cd ..
          tar czvf massa_unit_tests_${GITHUB_REF/refs\/tags\//}_${{ matrix.name }} massa_unit_tests
          cd -
          
          mkdir massa_sc_runtime_unit_tests && cd massa_sc_runtime_unit_tests
          cp -v ../build/massa-sc-runtime/*.wasm ./
          cp -v ../assembly/massa-sc-runtime/*.ts ./
          cd ..
          tar czvf massa_sc_runtime_unit_tests_${GITHUB_REF/refs\/tags\//}_${{ matrix.name }} massa_sc_runtime_unit_tests
          cd -
          
          ls -alh
